name: Make a Addition
labels: "Addition"
description: "Make a Addition"
assignees:
  - Muffinmaker2
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to make Augustus-Wiki great :D
  - type: textarea
    id: what-happened
    attributes:
      label: What is the Addition?
      description: Also tell us, what did you want to add?
      placeholder: Tell us!
      value: "Type your addition here"
    validations:
      required: true
