name: Form for Augustus Wiki
description: File a Addition/Correction.
title: "[Issue]: "
labels: ["Addition", "Correction"]
projects: ["Augustus-Bible"]
assignees:
  - Muffinmaker2
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to make Augustus-Wiki gread :D
  - type: checkboxes
    id: terms
    attributes:
      label: What you wanna do
      description: choose a option
      options:
        - label: Add something
        - label: Correct something
        required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What do you wanna have changed/Contribute?
      description: Write here what you wanna do
      placeholder: Tell us what you see!
      value: "Type stuff here"
    validations:
      required: true
